# Site settings
title:          Personal Notes
description:    "Study notes, personal opinions, and rants"
baseurl:        ""
url:            "https://sdsdkkk.github.io"

# Google Analytics
google_analytics: G-WMQJZNXL67

# Author
author:
  name:         Edwin Tunggawan
  url:          https://sdsdkkk.github.io
  email:        vcc.edwint@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale